image:
  file: .gitpod.Dockerfile
tasks:
  - name: Strapi
    init: >
      cd /workspace/strapi-project/api &&
      yarn install &&
      gp sync-done strapi
    command: yarn develop
ports:
  - port: 1337
    onOpen: open-browser
    visibility: public
  - port: 5173
    onOpen: open-browser
    visibility: public
